title: [Konrad's Portfolio]
description: [Thank you for visiting]
theme: jekyll-theme-cayman

# Navigation links
navbar:
  - title: Home
    url: /
  - title: Projects
    url: /projects
---
layout: page
title: Projects
permalink: /projects/
---

# Projects

Here are some of my projects:

- Project 1
- Project 2
- Project 3
